# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c5db80ee9acc57b87649fcb6938a5eb992bed933d2466a6912756bf98908da78d3c2104c92d257012349b98471d8683834ed8b6692ad36c2f7a6c4fe0fbc343f

test:
  secret_key_base: 1d0b1d110f37a0c8401f491238ea2b33e7f7f0aaff0572c9716e33c97ca550a8e09d4c58f6098b1859b9a226c925f80c2b49b41293c1eee9ae605396e7716212

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
